### ISSUE TITLE
我的

### ISSUE THREAD

**Issue by wetenrg** [kongxiangchx/Shopping-mall-management-system#3]
作者你好，我运行了项目之后注册没有跳转注册成功页面 而是说：进程已结束,退出代码-1073740791 (0xC0000409)该怎么解决

**Comment by kongxiangchx** [comment]
或许是mysql连接失败？可以看看mysql有没有启动，相应的表有没有建好

**Comment by jjj102684** [comment]
作者你好，我运行了项目之后注册没有跳转注册成功页面 而是说：
usr/bin/python3.10 /home/l/project/shopMain.py 
Traceback (most recent call last):
  File "/home/l/project/shopMain.py", line 41, in click1
    recv = s.message(data)
  File "/home/l/project/send_data.py", line 15, in message
    return json.loads(recvdata)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

该怎么解决

**Comment by jjj102684** [comment]
是要开什么服务吗/usr/bin/python3.10 /home/l/project/customerMain.py 
Traceback (most recent call last):
  File "/home/l/project/customerMain.py", line 39, in click1
    s = Send_data()
  File "/home/l/project/send_data.py", line 8, in __init__
    self.s.connect(('127.0.0.1', 5000))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/l/project/customerMain.py", line 39, in click

**Comment by jjj102684** [comment]
作者你端口搞错了吗

**Comment by HusterXqn** [comment]
作者你好，顾客端卡在了注册界面发生闪退，请问是什么原因

**Comment by xingxingyan-413** [comment]
找到原因了！！！！
您的客户端显示“注册失败”，是因为服务器在尝试执行 Shop_op.register() 方法时，连接数据库失败了。

诊断依据：
您的 MySQL 截图显示： 您的 MySQL 8.0 服务器在启动时要求您输入密码 (Enter password: ******)，这意味着您的 MySQL root 用户设置了密码。

您的 mysql_op.py 代码显示： 在连接配置中，您将密码设置为了空字符串 ('')。

作者的mysql_op.py部分的代码 里面的设置的空密码
失败的直接原因是 你的数据库设置了密码 而作者的没有改一下代码即可
# mysql_op.py (只需修改 Shop_op 和 Customer_op 中的 passwd)

class Shop_op:
    def __init__(self):
        self.host = 'localhost'
        self.user = 'root'
        self.passwd = 'YOUR_ACTUAL_MYSQL_PASSWORD'  # 替换成您的真实密码！！！！！！
        self.port = 3306
# ... (其他代码不变)

class Customer_op:
    def __init__(self):
        self.host = 'localhost'
        self.user = 'root'
        self.passwd = 'YOUR_ACTUAL_MYSQL_PASSWORD'  # 替换成您的真实密码！！！！！！！
        self.port = 3306
# ... (其他代码不变)

**Comment by xingxingyan-413** [comment]
> 作者你好，我运行了项目之后注册没有跳转注册成功页面 而是说：进程已结束,退出代码-1073740791 (0xC0000409)该怎么解决

找到原因了！！！！
您的客户端显示“注册失败”，是因为服务器在尝试执行 Shop_op.register() 方法时，连接数据库失败了。

诊断依据：
您的 MySQL 截图显示： 您的 MySQL 8.0 服务器在启动时要求您输入密码 (Enter password: ******)，这意味着您的 MySQL root 用户设置了密码。

您的 mysql_op.py 代码显示： 在连接配置中，您将密码设置为了空字符串 ('')。

作者的mysql_op.py部分的代码 里面的设置的空密码
失败的直接原因是 你的数据库设置了密码 而作者的没有改一下代码即可

mysql_op.py (只需修改 Shop_op 和 Customer_op 中的 passwd)
class Shop_op:
def init(self):
self.host = 'localhost'
self.user = 'root'
self.passwd = 'YOUR_ACTUAL_MYSQL_PASSWORD' # 替换成您的真实密码！！！！！！
self.port = 3306

... (其他代码不变)
class Customer_op:
def init(self):
self.host = 'localhost'
self.user = 'root'
self.passwd = 'YOUR_ACTUAL_MYSQL_PASSWORD' # 替换成您的真实密码！！！！！！！
self.port = 3306

... (其他代码不变)
